# Generated by Django 2.0.6 on 2019-10-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMVApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='imageFile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
